### ISSUE TITLE
[All charts] Rotate the date on xlabel 45 degree CCW

### ISSUE THREAD

**Issue by kystanleylin** [kystanleylin/COVID-19-Test-Positive-Rate#14]
As the timeline displayed gets longer, we might need to rotate the date displayed on the x-ticks 45 degrees counter-clockwise. It will improve the UX especially in prediction & mobile version.

<img width="549" alt="Screen Shot 2020-04-16 at 1 05 54 PM" src="https://user-images.githubusercontent.com/55610618/79485340-0cf66700-7fe3-11ea-97ad-0af6cdaf80de.png">

**Comment by oRonnyLin** [comment]
It should already be rotating, do you have an example?
