### ISSUE TITLE
Data: Add new cases per 100k residents to the test positive rate chart (low priority)

### ISSUE THREAD

**Issue by kl884** [kystanleylin/COVID-19-Test-Positive-Rate#18]
At the moment the test positive chart (one with only a blue line) is only relevant to some states, as the test positive rates in most states have already become stable. 

I was wondering if we could add the daily new cases per 100k residents to this chart in the orange color. The calculation for daily points is the same as what I described in the "Map" issue:

- New cases / state population * 100,000 (rounded to 2 decimal places, aligned with the test positive rate here)

Thanks!

**Comment by oRonnyLin** [comment]
The other graph I think suits the "daily" type of statistic better since it already features two other daily statistics. Do you have any ideas for cumulative type statistics?

**Comment by kl884** [comment]
What do you mean the other graph? The graphs on Data tab? Or the graphs on Prediction tab? The original thought was that the single blue line seems useless in some cases, but required for the states with high fluctuating test positive rate. So I was wondering if we could add something.

No inspirations for cumulative stats yet.

**Comment by oRonnyLin** [comment]
Added the new line in test positive chart. I also disabled the click to show points and limited the number of xticks.
