### ISSUE TITLE
Add user state to the tabs (low priority)

### ISSUE THREAD

**Issue by kl884** [kystanleylin/COVID-19-Test-Positive-Rate#19]
No sure how complicated this will be, but would you be able to record user state for "tabs" as well?

For example, GIVEN the user is in the "Data" tab, WHEN the user refreshes the webpage, THEN the user will still remain in the "Data" tab.

**Comment by oRonnyLin** [comment]
Nice suggestion! Will work on this first.

**Comment by oRonnyLin** [comment]
Done, I completed it first because it was just 2 lines of code.
