### ISSUE TITLE
Map: Change the display figures (medium priority)

### ISSUE THREAD

**Issue by kl884** [kystanleylin/COVID-19-Test-Positive-Rate#20]
In the "Map" tab, I was thinking if we could amend the figures displayed to as follows:

**[State Name]** _(this is the same)_
Kill **active cases** _(The data source does not have recovered/death data for certain states, eg. CA and WA. What do you think?)_
**avg. new cases per 100k residents for the past 7 days:** avg(new cases for the newest 7 data points)/state population*100,000 _(We have state population from the prediction, right?)_
**avg. test positive rate for the past 7 days:** sum(new cases for the newest 7 data points)/sum(test volume for the newest 7 data points)*100 _(as a percentage)_

The last 2 items can be rounded to 1 decimal places.

I thought this might reflect a more accurate situation in each state. This calculation is drawn from the "Restricted States" tab in [New York state COVID advisory](https://coronavirus.health.ny.gov/covid-19-travel-advisory). If the "for the past 7 days" is too long, maybe we can put it somewhere else as legend? (Whichever looks better)

The priority is relative to other issues. Not that this is urgent.

**Comment by oRonnyLin** [comment]
Ok, one question, where did the number 100k for 100k residents come from?

**Comment by kl884** [comment]
It came from NY State COVID Advisory. NYS hired McKinsey (global top consulting firm) for their COVID control. McKinsey must have come up with a metric to segment risky states and normal state. Daily 10 new cases per 100k residents is their threshold. In other words, anyone entering NYS from the risky states will have to self-quarantine for 14 days.

**Comment by oRonnyLin** [comment]
Made the changes to display those numbers on the map.
