### ISSUE TITLE
Tap anywhere to show info

### ISSUE THREAD

**Issue by kystanleylin** [kystanleylin/COVID-19-Test-Positive-Rate#3]
1point3acres have the same problem, so they allow users to click anywhere on the graph and draw a thin vertical line.

![S__25837796](https://user-images.githubusercontent.com/55610618/79310462-ff00f300-7ec9-11ea-8b2d-0512b920532b.jpg)

**Comment by oRonnyLin** [comment]
You can now tap on the graph to display points.

When you hover anywhere on the graph or touch, a vertical cursor line will show at the nearest index.
