### ISSUE TITLE
Meta tag of the website

### ISSUE THREAD

**Issue by kystanleylin** [kystanleylin/COVID-19-Test-Positive-Rate#4]
With a screen preview of the front page as the image

![S__25837825](https://user-images.githubusercontent.com/55610618/79310998-ca416b80-7eca-11ea-814e-96bea1a343c3.jpg)

**Comment by oRonnyLin** [comment]
Added the following meta tags
```
    <meta property="og:title" content="COVID-19 Update by State">
    <meta property="og:description" content="COVID-19 tracking project by state with test positive rate and bass model prediction.">
    <meta property="og:image" content="https://66.media.tumblr.com/fe9d150445ea7ae58786adb72ad633a5/bdd9aadbbfd13eab-79/s640x960/519fb5d28bb4f937030e005a2c676172d26fa7e5.jpg">
    <meta property="og:url" content="http://54.244.209.103/">
```
I am not sure if this satisfies the requirement for LinkedIn. It didn't show up as expected when I tested it by uploading it on my profile, but both the Facebook and Linkedin post inspector show up ok.

https://developers.facebook.com/tools/debug/?q=http%3A%2F%2F54.244.209.103

https://www.linkedin.com/post-inspector/inspect/http:%2F%2F54.244.209.103%2F

**Comment by kystanleylin** [comment]
Lol appreciate the effort, but probably not memes on LinkedIn hahaha

Could you set the image as what the user will see on the front page?

**Comment by oRonnyLin** [comment]
lol just a placeholder, image updated
