### ISSUE TITLE
Find a better favicon

### ISSUE THREAD

**Issue by kystanleylin** [kystanleylin/COVID-19-Test-Positive-Rate#5]

**Comment by kystanleylin** [comment]
Two options:

1. https://www.vectorstock.com/royalty-free-vector/puzzle-pieces-game-icon-vector-19640480
![IMG_1932](https://user-images.githubusercontent.com/55610618/79355707-06e18700-7f0c-11ea-9e6b-8528e49011e3.jpg)

2. https://www.stockio.com/free-icon/buster-icon-set-puzzle
![puzzle@3x](https://user-images.githubusercontent.com/55610618/79355736-1365df80-7f0c-11ea-8ef6-8b992420cbbc.png)

**Comment by oRonnyLin** [comment]
These are nice!

**Comment by kystanleylin** [comment]
Personally prefer the first one

**Comment by oRonnyLin** [comment]
It's not free when I try to download it.

**Comment by kystanleylin** [comment]
Just use the png I sent you for now 🙃
